### ISSUE TITLE
Custom Container Support?

### ISSUE THREAD

**Issue by kbroughton** [FSecureLABS/awspx#29]
Hi, thanks for this project!

The INSTALL script pulls from a pure neo4j container and then installs a bunch of stuff. That slows deployment and means that it could break at anytime as libs change. Is there any reason you don't use a Dockerfile to bake all the necessaries into the project? Would you accept a PR for one?

**Comment by beatro0t** [comment]
Hey @kbroughton, thanks for the issue!

To answer your question, mainly because I'm not too clued up on Dockerfiles and personally find BaSH to be a lot more flexible. That being said I know this isn't a sentiment shared by many and a PR would be more than welcome, thank you :) 

In regard to deployment, and libs breaking, is this for reinstalls or new deployments? The reason I ask is because v1.2 will include an `update`  CLI option (which will just pull awspx changes without rebuilding the whole container). If this is something that would be useful to you now, it's currently available in the dev branch.

**Comment by beatro0t** [comment]
Dockerfile added in Release 1.3.0
