### ISSUE TITLE
Crashing at (InvalidInstanceID.NotFound)

### ISSUE THREAD

**Issue by ayysasha** [FSecureLABS/awspx#4]
Hello All,

Running Flags:
`ingest --region=[single region] --except-types "AWS::S3::Object" --services="EC2"`

Am getting a crash after 1-2hrs of runtime:

```
Traceback (most recent call last):
  File "/opt/awspx/cli.py", line 395, in <module>
    main()
  File "/opt/awspx/cli.py", line 390, in main
    args.func(args)
  File "/opt/awspx/cli.py", line 135, in handle_ingest
    only_arns=args.only_arns, except_arns=args.except_arns)
  File "/opt/awspx/lib/aws/ingestor.py", line 837, in __init__
    self.get_instance_user_data()
  File "/opt/awspx/lib/aws/ingestor.py", line 859, in get_instance_user_data
    InstanceId=name)
  File "/usr/local/lib/python3.7/dist-packages/botocore/client.py", line 272, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/botocore/client.py", line 576, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidInstanceID.NotFound) when calling the DescribeInstanceAttribute operation: The instance ID '[censored instance ID]' does not exist

```

Running this in docker on Mac OS 10.14.6. Did not have this issue with smaller aws regions.

**Comment by masteryeets** [comment]
Hey @ayysasha, thanks for reporting this. I've recently come across the same issue in my own use of the tool. It seems to come up when EC2 instances go down while the tool is busy ingesting. https://github.com/FSecureLABS/awspx/commit/20765e4f154523fc2a94c83abe1630a17678ac26 should fix it.

**Comment by beatro0t** [comment]
@ayysasha  Thanks for the detailed information - as an aside, unless your'e not interested in what actions can be performed on EC2 resources, I'd recommend running the following: 

```
awspx ingest --region=[single region]  --services IAM EC2 
```

If your aim is just to explore EC2 resources (whats associated with what and resource properties) and not the actions that affect them, I'd recommending skipping attacks altogether by appending `--skip-attacks` (attack computation relies on actions being present - we should probably just update the ingestor to ignore this step if IAM hasn't been included). 

Something else that may be of interest to you is who can potentially read EC2 volumes (its presently commented out because its not really a global case). If you wish to include this information,  uncomment the following:

https://github.com/FSecureLABS/awspx/blob/82687e789a244ae1e13ab064caea1e3150a8ca40/lib/aws/attacks.py#L417-L440

Please let us know if the problem persists or if you run into any trouble :)

**Comment by ayysasha** [comment]
Thanks for the tips. At this stage I was parting out my ingestion by resource group as some of these groups have 100k+ individual objects. Im going to try and give it another go with the patch and report back.

**Comment by beatro0t** [comment]
Wow! Unfortunately, at that scale it is likely the ingestor will crash or go on indefinitely. The problem is that for each resource there can be a few hundred actions associated with it, each of which will be stored as its own edge. So if we're talking about 100k+ resources, we could be talking about relationships in the order of a few hundred times that for each policy affecting these resources. 

Right now action information is stored in a list (which we search for duplicates - it needs to be changed to a set) before writing to the CSVs that ultimately get imported into the db. I'd recommend commenting out this line to skip action resolution altogether, in these cases: 

https://github.com/FSecureLABS/awspx/blob/9d293fc4355a69c95f0ad62697b142667591d5b9/lib/aws/ingestor.py#L623

I'm trying to think of a sensible way to write out this information in stages, rather than in one shot so that we can better handle environments of this magnitude. In any event, we're very interested in hearing about the outcome.

**Comment by ayysasha** [comment]
It seems now that toward the end of ingestion (of about 10k ec2 instances) the program exists with 0, and the results dont get written. This happened after about 6 hrs of runtime. This seems to most likely be a separate issue from the one stated above.

**Comment by beatro0t** [comment]
That is peculiar. Unfortunately we do not have access to a large enough environment to try and recreate this issue. I've just pushed an update to enable increasing output verbosity. Would you mind rerunning the ingestor with the following arguments and letting us know what it last prints if it exits cleanly again without writing to the database:
```
awspx ingest --services EC2 --skip-actions --verbose
```

**Comment by beatro0t** [comment]
Hi @ayysasha, just checking in to see whether or not you've had an opportunity to test again with the aforementioned changes?

**Comment by ayysasha** [comment]
sorry just getting back to this now, yes, it ended up working after pulling new vers.

it takes about 40 hrs but it is working!

**Comment by ayysasha** [comment]
* working with no flags, just "ingest" and it runs/completes/works
