### ISSUE TITLE
Error when calling STS assume role

### ISSUE THREAD

**Issue by Leectan** [FSecureLABS/awspx#49]
I have assume role profile set, as well as using the assume role STS returned credentials set as environment variables, but non of the method works. Looking at cli.py, looks like assume role is supported but was not part of the parameters when creating new profile. 

<img width="1100" alt="com_docker_cli" src="https://user-images.githubusercontent.com/24819052/126081073-9b5d47fd-368d-4599-9bb1-950237ed107f.png">

**Comment by dmyates** [comment]
Hi Leectan,

awspx uses credentials set inside its docker container, which you configure when setting up a profile, so it will ignore environment variables.

You can ingest using an assumed role by setting up a profile with a user who is able to assume that role, and then passing  `--assume-role` with the ARN of the role to assume to `aws ingest`. Additional parameters will allow you to pass in external ID and MFA details where necessary.

**Comment by beatro0t** [comment]
100% @dmyates! 

@Leectan, what you may be looking for is  [`--env`](https://github.com/FSecureLABS/awspx/wiki/Data-Collection#ingestion), which will pass the following envirionment variables directly to the container when calling `awspx ingest`:

 * `AWS_ACCESS_KEY_ID`
 * `AWS_SECRET_ACCESS_KEY`
 * `AWS_SESSION_TOKEN`
 * `AWS_SECURITY_TOKEN`

**Comment by Leectan** [comment]
@dmyates Tried your step, didn't work. Profile is set correctly, I was able to assume the role just FYI.
<img width="460" alt="-bash" src="https://user-images.githubusercontent.com/24819052/126193247-a7807822-b5a1-4abe-b173-4cd3dfbae3dd.png">


<img width="971" alt="Cursor_and_-bash" src="https://user-images.githubusercontent.com/24819052/126193143-cd630b50-7185-4485-a568-f19b3f1ab7f7.png">

**Comment by Leectan** [comment]
@beatro0t, what you suggested are already in the README.md, which I called out above. BTW, there is no AWS_SECURITY_TOKEN, only SESSION_TOKEN.

**Comment by beatro0t** [comment]
@Leectan, I'm not sure I follow. The above error indicates you have successfully authenticated but are not authorized to assume the role. What is not working for you? 

Please clarify what it is you are trying to do and include the command-line arguments producing the unexpected behaviour.

**Comment by Leectan** [comment]
@beatro0t I'm trying to run this with assume role, thats it, and using aws credential profile specified in ~/.aws/credentials and assume role generated temporary credentials all returned error.

**Comment by beatro0t** [comment]
As @dmyates pointed out, awspx runs in a container. You would need to edit the credentials file in the container itself for that method to wok: i.e. `docker exec -it awspx sh -c 'apt update && apt install vim && vim ~/.aws/credentials'`. 

Alternatively, you can export those values to environment variables listed previously outside of the container and run `awspx ingest --env` (which will pass those values to the container - you do not need to export everything, only values that are applicable). 

If the error you are referring to is the most recent screenshot you posted, everything appears to be working as expected (i.e. you have successfully authenticated as a user but that user is not authorized to perform sts:AssumeRole - this would suggest this is an access control issue). You can test with the aws cli: `aws sts assume-role --role-arn $role_arn --role-session-name test`  to verify whether this is the case. 

Again, please include the full command you are issuing with each error encountered, otherwise we cannot assist.

**Comment by Leectan** [comment]
@beatro0t thank you much on your info and time, the docker command was something I missed.

**Comment by beatro0t** [comment]
No problem at all, very to happy to hear you came right!
