### ISSUE TITLE
awspx ingest --env not working

### ISSUE THREAD

**Issue by Kamerabuilt** [FSecureLABS/awspx#51]
Hi!

First, thanks for the tool. 

I exported my env variables for STS tokens, and they are working fine, ie. if I do **aws s3 ls** or **aws sts get-caller-identity**, they work as expected (without having anything under .aws/config or .aws/credentials), in my host machine. 

However, when I run sudo awspx ingest --env, it fails with the following output: 
  →   Awaiting response to sts:GetCallerIdentity  
... bunch of output in table-format
NoCredentialsError: Unable to locate credentials 

Since I would like to use env variables, I have not created any profiles, therefore the following command has no output: 
sudo awspx profile --list 

I also ran sudo docker exec -it awspx bash , and did env as well as trying to run a command such as aws s3 ls, it says unable to locate credentials. It seems that the STS tokens are not being passed to the docker container...

Am I doing anything wrong?

**Comment by beatro0t** [comment]
Hi @Kamerabuilt, thanks for reporting the issue!

Which specific environment variables are you exporting?  The CLI is basically just a wrapper for the following command (and  will currently only pass the following  environment variables): 

https://github.com/FSecureLABS/awspx/blob/9f71ef23ab26cc4fc6b61cdfb2e8d6beb7d95742/INSTALL#L164-L169

If you run `sudo docker exec -it -e ... awspx aws s3 ls`  with each of these variables,  does it succeed?

**Comment by Kamerabuilt** [comment]
Hi, thanks for your reply. Here are the commands I ran, with the output of each, it should give us an idea what is going on: 

1) sudo awspx ingest **--env** --skip-types AWS::S3::Object 
NoCredentialsError: Unable to locate credentials

2) sudo docker exec -it -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN -e AWS_SECURITY_TOKEN=$AWS_SECURITY_TOKEN **awspx aws s3 ls** 
2021-07-17 21:27:58 <bucket1>
2021-07-31 18:04:37 <bucket2> 

3) Ran again the first command, same result: Unable to locate credentials 

4) Tried this command (notice the -E with the sudo), and it does work:  sudo -E awspx ingest **--env** --skip-types AWS::S3::Object 

I think it is related to the docker command not being able to pass the STS credentials to the docker container with that --env switch, but it does work if we do docker exec -e , or, we do sudo -E 

Any ideas what could it be?

**Comment by beatro0t** [comment]
Thanks @Kamerabuilt, glad to hear you found a workable solution!

As you pointed out, `sudo -E` preserves environment variables so the values you exported, along with everything else in your environment, will be made available to the CLI when it invoked in a root context after the sudo takes place. If you omit this flag, those values will be empty when the CLI tries to resolve them. It will subsequently pass along empty values to the container, resulting in the errors you encountered. It will work when you pass those values to docker with sudo because the commandline variables will be resolved before the "sudo" actually takes place. 

I'd recommend making use of `--preserve-env=AWS_ACCESS_KEY_ID,AWS_SESSION_TOKEN,AWS_SECURITY_TOKEN` instead of `-E`, or checking out some of the other options (https://wiki.archlinux.org/title/Sudo#Environment_variables)  so you don't have to preserve everything.

I've updated the FAQs page to include this information for anyone else who may run into this [issue](https://github.com/FSecureLABS/awspx/wiki/FAQs#why-doesnt-sudo-awspx-ingest---env-work)

**Comment by Kamerabuilt** [comment]
Thanks for your reply!

I am still trying to figure out why am not able to export variables "the normal way". I added the local user to the docker group, and while I can now run docker without sudo, I am still not able to export the terminal env vars to the docker container without that -E. 

However, I believe all this is related to docker and permissions, so I think we can close this issue :)
