### ISSUE TITLE
easier RUN and non local build

### ISSUE THREAD

**Issue by saryx123** [FSecureLABS/awspx#6]
Hi,

I'm having a hard time running awspx on a remote machine, while I do intent to access the web console from my work laptop. 

1. There is an install instruction, but not a run instruction. Install pulls, downloads and builds anew - thus time and data are lost. How do I just run this easily?

2. It seems just changing the HOST= line in INSTALL is not sufficient, as the webpage directs the browser to other local ports (such as 7687), not only that, the app does so directing the browser to HOST ip at :PORT, this wont do in cases where the local server is not aware of his external IP.
How do I set awspx up for remote use, rather than just a local tool?

**Comment by beatro0t** [comment]
Hi @saryx123,

Run instructions have been comprehensively documented in the Readme, see: [Quick Start](https://github.com/FSecureLABS/awspx/blob/master/README.md#quick-start) and [Data Collection](https://github.com/FSecureLABS/awspx/blob/master/README.md#data-collection) for more information. You can also run `awspx -h` for help. 

Rerunning `INSTALL` will delete all existing databases; however, all data located in `/opt/awspx/data` will not be touched. This means you can load previously collected data by running `awspx db --load-zip ` after reinstalling without having to run the ingestor again. 

Can you verify you are running the latest version of `awspx`? Changing the `HOST` line in INSTALL should be sufficient for remote use (the webpage will use this value as well) - just make sure you set it to an external interface value before running `INSTALL`, if you want it to be reachable from the network. Alternatively, you can try leaving the `HOST` line as is, and connect to it over an SSH tunnel if you are planning on connecting to it over the internet.

Please let me know if the problem persists.

**Comment by saryx123** [comment]
Hi, thanks for taking the time to respond!

- the awspx local data folder and opt/awspx/data are cempty with the exception of sample, following an INSTALL, ingest data did not persist. Which is not great.
- There are no RUN instructions documented, there's quickstart, install, datacollection and more, bot NO RUN instructions. All the sections either explain how to install the first time or assume that the the docker is running. It is not a fair assumption. 
-  How do I determine the version? AWSPX is not installed with a package manager, there is not command for it (awspx -h does not show anything helpful). I can tell that the initial pull occurred Feb 4th.

**Comment by beatro0t** [comment]
Hi @saryx123,

Its an absolute pleasure, sorry about the delay. 

* `/opt/awspx` is a mount point on your host. Reinstalling will delete the container and create a new one, which mounts this same mount point. I cannot see how this data would not persist and cannot recreate this issue. Can you verify your ingested data is being removed by: running the ingestor; listing the zip it creates; reinstalling; and then listing `/opt/awspx/data` again to verify it no longer exists?

* Data collection and run are one and the same thing: you are running the data collector. Is your issue with how the section has been titled? There are no instructions for docker (save for the install guide) because the the command line utility checks for it (i.e. if it is not running, it will tell you; if it is not installed, it will tell you). I feel like including it with the "run" instructions would be a bit redundant. I'm not sure where the difficulty here lies so please feel free to make changes to the documentation by submitting a PR.

* You are absolutely correct, sorry about the confusion. What I meant was: if you do a `git pull` is it up to date, but you have answered my question; I was wondering whether you had pulled prior to  99076a91efe14248f43ca7b2264f280a26b57313, but the version you are using already includes this commit.

**Comment by saryx123** [comment]
- Looking into reproduction of the issue per reinstall data & profiles persistence.

- I'm not sure i'm passing through with my primary issue. AWSPX frontend does not operate when the docker (awspx) install occurs on a remote machine and you browse to it from another IP. I dont run docker locally, too little ram, too many chrome tabs. Even when you amend the HOST variable (to 0.0.0.0 or another local address) in the install file and the frontend index page loads - the dependencies dont (http://0.0.0.0/sockjs-node/info?t=1582638469145). This is because 0.0.0.0 is NOT an address accessible remotely.

Can one install awspx in a way that would make it accessible remotely?

**Comment by beatro0t** [comment]
You could install awspx on the remote machine (without making any changes) and create a local SSH tunnel to expose the remote ports locally. E.g: 
```
ssh -L 80:127.0.0.1:80 -L 7373:127.0.0.1:7373 -L 7474:127.0.0.1:7474 -L 7687:127.0.0.1:7687 ${username}@${remote_host}
```
Then just browse to http://localhost as you would if it was installed locally. 

Alternatively you can change `HOST`: it must be a routable external address (i.e. whatever your remote hosts address is: e.g. `10.0.0.100`), `0.0.0.0` is not routable.  

https://github.com/FSecureLABS/awspx/blob/eaafb33a0eca009ff6f55012bded8e5811837176/INSTALL#L6
